"""add fingerprint and trends support

Revision ID: 1a5abd1eb29e
Revises: 5208984d7a9c
Create Date: 2026-04-01 12:19:38.070032
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5abd1eb29e'
down_revision: Union[str, None] = '5208984d7a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_fingerprint'), 'jobs', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_fingerprint'), table_name='jobs')
    op.drop_column('jobs', 'fingerprint')
    # ### end Alembic commands ###
